@startuml
'https://plantuml.com/class-diagram

abstract class Transportmiddel {
    + ID : int
    + AntallPassajerer : int
    + AntallTilgjengelig : int
}

Buss <|-- Transportmiddel
Tog <|-- Transportmiddel
Baat <|-- Transportmiddel
Trikk <|-- Transportmiddel

class Buss {
}
class Tog {
}
class Baat {
}
class Trikk {
}

'--------------------------'
abstract class Bruker {
    + ID : int
    + Fornavn : String
    + Etternavn : String
    + E-post : String
}

Kunde <|-- Bruker
Admin <|-- Bruker
Developer <|-- Bruker

class Kunde {
}
class Admin {
}
class Developer {
}

'--------------------------'

class Rute {
    + ID : int
    + Navn : String
    + ArrayList<Rute> : Rute
    + StartDatoTid : DateTime
    + SluttDatoTid : DateTime
    + Transportmiddel : Transportmiddel
}
class Stopp {
    ID : int
    Navn : String
    Adresse: String
}
class Kart {
}

'--------------------------'

class Betaling {
}
class Billett {
}
class innlogging {
}

'--------------------------'
class SoekResultat {
    ArrayList<Rute>Ruter : ArrayList<Rute>
}

'Eksempler'
/'interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}'/

@enduml